apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  strategy: {}
  template:
      metadata:
        labels:
          app: test
      spec:
       containers:
       - image: ikanpaus/nginxrma:v1
         name: test-rma
         ports:
         - containerPort: 80
         resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: testserpis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
     app: test
  type: LoadBalancer 
status:
  loadBalancer: {}
